name       : perl-algorithm-diff
version    : '1.201'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Algorithm-Diff-1.201.tar.gz : 0022da5982645d9ef0207f3eb9ef63e70e9713ed2340ed7b3850779b0d842a7d
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Algorithm::Diff - Compute `intelligent' differences between two files / lists
description: |
    Algorithm::Diff - Compute `intelligent' differences between two files / lists
builddeps  :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
