name       : perl-algorithm-diff
version    : 1.1903
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/T/TY/TYEMQ/Algorithm-Diff-1.1903.tar.gz : 30e84ac4b31d40b66293f7b1221331c5a50561a39d580d85004d9c1fff991751
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Algorithm::Diff - Compute `intelligent' differences between two files
    / lists
description: |
    Algorithm::Diff - Compute `intelligent' differences between two files / lists
builddeps  :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
